// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250714092338_testdata")]
    partial class testdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Phone description",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "Iphone 15",
                            Price = 7000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "Phone description",
                            ImageUrl = "2.jpg",
                            IsActive = true,
                            Name = "Iphone 16",
                            Price = 8000m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 3,
                            Description = "Phone description",
                            ImageUrl = "3.jpg",
                            IsActive = true,
                            Name = "Iphone 17",
                            Price = 9000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 4,
                            Description = "Phone description",
                            ImageUrl = "4.jpg",
                            IsActive = true,
                            Name = "Iphone 18",
                            Price = 10000m,
                            Stock = 800
                        },
                        new
                        {
                            Id = 5,
                            Description = "Phone description",
                            ImageUrl = "5.jpg",
                            IsActive = true,
                            Name = "Iphone 19",
                            Price = 11000m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 6,
                            Description = "Phone description",
                            ImageUrl = "6.jpg",
                            IsActive = true,
                            Name = "Iphone 14",
                            Price = 6000m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 7,
                            Description = "Phone description",
                            ImageUrl = "7.jpg",
                            IsActive = true,
                            Name = "Iphone 13",
                            Price = 5000m,
                            Stock = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
